version: "3"

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
